use anacredit

--[src].[EDW_com_BIC_DIRECTORY]
--SELECT * FROM stg.F_BIC WHERE BIC LIKE 'ETHNCYNN%'


--ANACRD_T_Anacredit_STG_F_BIC_M.dtsx: EDW.com.BIC_DIRECTORY -> stg.F_BIC
SELECT * FROM EDW.com.BIC_DIRECTORY WHERE BIC = 'ETHNCYNNXXX' AND DT_EFF<='2024-02-29' AND DT_END>'2024-02-29'--YPARXEI
SELECT * FROM EDW.com.BIC_DIRECTORY WHERE BIC = 'ETHNCYNNXXX' AND DT_EFF<='2024-03-31' AND DT_END>'2024-03-31'--MISSING

SELECT TOP 10 * FROM ANACREDIT.[src].[FILE_BLOOMBERG_PER] 


SELECT 

 CONVERT (DATETIME,@ReportingDate) AS REF_DT
,cast('GR011' as nvarchar(30) ) AS REP_A_ID
,cast('GR011' as nvarchar(30) ) AS OBS_A_ID
,ISNULL(biccst.BIC, 'NA') AS CID
,cast('BIC' as nvarchar(30)) AS NIDT
,  biccst.BIC AS NID
,cast('' as nvarchar(9)) AS AFM
,cast('' as nvarchar(10)) AS IMO
,cast('' as nvarchar(12)) AS GEMH
,biccst.ISO_LEI_CODE AS LEI
,ISNULL(blm.DATE_OR_YEAR_OF_INCORPORATION, '1900-01-01') AS ESD --'1900-01-01' AS ESD
,ISNULL(TH.BIC, '') AS HOUID
,ISNULL(TL.BIC, '') AS IPUID
,ISNULL(TG.BIC, '') AS UPCID
,SUBSTRING(biccst.INSTITUTION_NAME,1,100) AS NAME
,SUBSTRING (CONCAT (biccst.STREET_ADDRESS_1,biccst.STREET_ADDRESS_2,biccst.STREET_ADDRESS_3,biccst.STREET_ADDRESS_4),1,100) AS ASTR
,biccst.CITY AS AC
,CASE WHEN biccst.ISO_COUNTRY_CODE collate Greek_CI_AI = 'GR' THEN 'ELZZZ'
	ELSE CASE WHEN biccst.ISO_COUNTRY_CODE collate Greek_CI_AI = 'GB'  THEN 'UKZZZ' 
	ELSE acty.ACTY 	END 
	END  
	AS ACTY
,biccst.[ZIP CODE] AS APC
,cast(biccst.ISO_COUNTRY_CODE as char(2)) AS ACTR
,cast(ISNULL(LF.LF, 'RW600') as nvarchar(10))	AS LF			
,cast(CASE WHEN biccst.BIC8 = 'BNGRGRAA' THEN 'S121' ELSE 'S122_A' END as nvarchar(10))  AS ISCTR
,cast('64' as nvarchar(10)) AS EA
,'1' AS SLP
,'1900-01-01' AS DILP
,'0' AS ES
,@ReportingDate AS DES
,ISNULL(blm.[NUM_OF_EMPLOYEES], 0) AS NE
,ISNULL(blm.[BS_TOT_EQY], 0)*POWER(10, 6) AS BST -- 0 AS BST
,ISNULL(blm.[TRAIL_12M_NET_SALES], 0)*POWER(10, 6) AS AT --0 AS AT --

, CASE WHEN biccst.BIC = 'ETHNGRAAXXX' THEN '2' ELSE '' END AS AST -- according to specs
, CASE WHEN biccst.BIC = 'ETHNGRAAXXX' THEN '1' ELSE '0' END  as CR -- JOB_X WILL POPULATE THIS FIELD
, cast(CASE WHEN biccst.BIC = 'ETHNGRAAXXX' THEN '' ELSE '1' END as nvarchar(1)) as OLD -- JOB_X WILL POPULATE THIS FIELD

,cast('0' as nvarchar(1)) AS PR
,cast('0' as nvarchar(1)) AS HO
,cast('0' as nvarchar(1)) AS PAR
,cast('0' as nvarchar(1)) AS UP
,cast( CASE WHEN biccst.BIC = 'ETHNGRAAXXX' THEN '1' ELSE '0' END as nvarchar(1))  as OCR -- JOB_X WILL POPULATE THIS FIELD
,cast( CASE WHEN biccst.BIC = 'ETHNGRAAXXX' THEN '1' ELSE '0' END as nvarchar(1)) as SRV -- JOB_X WILL POPULATE THIS FIELD
,CURRENT_TIMESTAMP AS INSERT_TIMESTAMP
,@RunID  AS INSERT_ETL_RUN_ID
,cast('BIC' as char(15)) AS SOURCE_SYSTEM_ID -- 'EDW'
,cast( '0' as nvarchar(1)) AS QUALIFICATION_FLAG -- CASE WHEN 
,@DataVersion AS DATA_VERSION
,0 AS [DEL_APPV_DIV_ID]
,0 AS [DEPT_APPV_DIV_ID]
,cast('' as nvarchar(40)) AS EM 
, cast('' as nvarchar(30)) AS PH
FROM EDW.com.BIC_DIRECTORY biccst

LEFT JOIN [dbo].[REF_LF_TYPE] LF		--ANACREDIT.LF_TYPE 
ON CASE WHEN ISNULL(biccst.ISO_COUNTRY_CODE, '') = 'GR' 
	THEN 'OTH' ELSE '' END  = LF.LEG_TYPE_ID 
	AND ISNULL(biccst.ISO_COUNTRY_CODE, '')  = LF.CTRY  collate Greek_CI_AI

LEFT JOIN [dbo].[REF_ACTY_TYPE] acty
ON CASE WHEN biccst.ISO_COUNTRY_CODE <> 'GR' THEN biccst.ISO_COUNTRY_CODE  ELSE '' END = acty.ACTR collate Greek_CI_AI

LEFT JOIN 
(SELECT LEGAL_ENTITY_IDENTIFIER, NUM_OF_EMPLOYEES, DATE_OR_YEAR_OF_INCORPORATION, BS_TOT_EQY, TRAIL_12M_NET_SALES
FROM [src].[FILE_BLOOMBERG_PER] 
GROUP BY LEGAL_ENTITY_IDENTIFIER, NUM_OF_EMPLOYEES, DATE_OR_YEAR_OF_INCORPORATION, BS_TOT_EQY, TRAIL_12M_NET_SALES) blm
ON biccst.ISO_LEI_CODE = blm.[LEGAL_ENTITY_IDENTIFIER]

LEFT JOIN stg.F_BIC TH
ON biccst.HEAD_OFFICE_KEY = TH.RECORD_KEY --AND R.BIC &lt;&gt; TH.BIC


LEFT JOIN stg.F_BIC TL
ON biccst.LEGAL_PARENT_KEY = TL.RECORD_KEY --AND R.BIC &lt;&gt; TL.BIC

LEFT JOIN stg.F_BIC TG
ON biccst.GROUP_PARENT_KEY = TG.RECORD_KEY --AND R.BIC &lt;&gt; TG.BIC



--NATIONAL BANK OF GREECE S.A. CYPRUS BRANCH (578)
SELECT TOP 10 * FROM ANACREDIT.dbo.CRD WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-02-29'--YPARXEI
SELECT TOP 10 * FROM ANACREDIT.dbo.CRD WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-03-31'--MISSING
SELECT TOP 10 * FROM ANACREDIT.dbo.CRD_SUB WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-02-29'--YPARXEI
SELECT TOP 10 * FROM ANACREDIT.dbo.CRD_SUB WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-03-31'--INSID

--1238120ADPTV MISSING
--1250575ADPTV MISSING
SELECT * FROM ANACREDIT.dbo.CID WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-02-29' ORDER BY INSID--YPARXEI 
SELECT * FROM ANACREDIT.dbo.CID WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-03-31' ORDER BY INSID--MISSING

SELECT * FROM ANACREDIT.dbo.CID WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-02-29' ORDER BY INSID--YPARXEI 
SELECT * FROM ANACREDIT.dbo.CID WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-03-31' ORDER BY INSID--MISSING

SELECT TOP 10 * FROM EDW.cst.CST WHERE CST_NM

SELECT * FROM dbo.SPRT_CST_ADD ORDER BY CID_OLD

[cst].[CST_MIGR]

SELECT TOP 10 * FROM EDW.CST.ORG_FIN_STMNT_DTLS
SELECT TOP 10 * FROM [dbo].[REF_ACTY_TYPE]







"
----------------------- extra records NICOSIA KYPROY ---------------------------------------------------

DECLARE @DATA_VERSION NVARCHAR(10);
DECLARE @ReportingDate datetime ;
DECLARE @OBS varchar(20) ;
DECLARE @RunID int;
DECLARE @CID NVARCHAR(30);
DECLARE @CNID NVARCHAR(30);
DECLARE @OUTAM NUMERIC(18,2);

SET @RunID = 1 ;
SET @ReportingDate = '"+ @[User::varReportingDate] +"' ;
SET @DATA_VERSION	=convert(nvarchar(10), @ReportingDate, 112 )+'0'+cast(@RunID as char(1));
SET @OBS = 'GR011';

USE Anacredit
SELECT * FROM [src].[FILE_TREASURY_PRTF] 
WHERE CounterParty='ETHNCYNNXXX'


select top 100 CID, * from anacredit.dbo.CRD_SUB where CID = 'ETHNCYNNXXX' AND REF_DT='2024-03-31'

--208,778,887.72
select top 100
       REF_DT, QUALIFICATION_FLAG, SOURCE_SYSTEM_ID, CID, CNID, INSID, *
--SELECT SUM(IFD_SUB.OUTAM) OUTAM
from anacredit.dbo.CID_SUB
--left join anacredit.dbo.ifd_sub on ifd_SUB.INSID = CID_SUB.INSID AND IFD_SUB.REF_DT = CID_SUB.REF_DT
where CID_SUB.CID = 'ETHNCYNNXXX' AND CID_SUB.REF_DT='2024-03-31'
AND CID_SUB.SOURCE_SYSTEM_ID='ADPTV'
ORDER BY CID_SUB.QUALIFICATION_FLAG

select top 100
       REF_DT, QUALIFICATION_FLAG, SOURCE_SYSTEM_ID, CID, CNID, INSID, *
from anacredit.dbo.CID
where CID = 'ETHNCYNNXXX' AND REF_DT='2024-03-31'

SELECT * FROM ANACREDIT.DBO.CID_SUB WHERE INSID='1297409ADPTV' AND REF_DT='2024-02-29'





--1297409ADPTV
SELECT *
FROM anacredit.dbo.CID_ADD
WHERE CID='ETHNCYNNXXX'
--ANAPV081 ANACRD_T_ANACREDIT_GR011_DBO_CID_SUB_M.DTSX
--\\S000013845\WINSCHED\ANA\PACKAGES\ANACRD_E_DELTA_EO_CID_SUB_M.DTSX DEN BGAZEI DELTA

and cur.data_version = '2024033101'
and  pre.data_version = '2024022901'
2024013101


select cur.* from cid_sub cur
where-- cur.data_version = '2024022901' AND 
cur.INSID='1297409ADPTV'
ORDER BY REF_DT, CRL

SELECT TOP 10 * FROM  [dbo].[ANACREDIT_DQA]
WHERE S_REF_DT='2024-03-31' AND S_OBS_A_ID='GR011'



--ANAPV276
--ANAPV277 ANACRD_E_DELTA_EO_CRD_SUB_M.DTSX
--ANAPV309 ANACRD_E_DELTA_EO_IFD_SUB_M.DTSX
--ANAPV316 ANACRD_E_DELTA_EO_IPRD_SUB_M.DTSX
--ANAPV330
--ANAPV331
--ANAPV332 \\S000013845\WINSCHED\ANA\PACKAGES\ANACRD_E_NEW_EO_CID_SUB_M.DTSX EINAI AKOMA Q=1
--ANAPV333 ANACRD_E_NEW_EO_CRD_SUB_M.DTSX
--ANAPV334 ANACRD_E_NEW_EO_IFD_SUB_M.DTSX
--ANAPV335, 
--ANAPV336 ANACRD_E_NEW_EO_JLD_SUB_M.DTSX
--ANAPV337 ANACRD_E_NEW_EO_PRD_SUB_M.DTSX
--ANAPV354, ANAPV433, ANAPV434, ANAPV435, ANAPV436, ANAPV437, ANAPV438


SELECT QUALIFICATION_FLAG, * from anacredit.dbo.CID WHERE INSID='1224596ADPTV' AND REF_DT='2024-03-31'
SELECT QUALIFICATION_FLAG, * from anacredit.dbo.CID_SUB WHERE INSID='1224596ADPTV' AND REF_DT='2024-03-31'
SELECT TOP 10 * FROM anacredit.[dbo].[ANACREDIT_CID_DQ_ERR] WHERE  INSID='1250557ADPTV'
SELECT TOP 10 * FROM anacredit.[dbo].[ANACREDIT_CID_DQ_ERR] WHERE CID='ETHNCYNNXXX'

SELECT QUALIFICATION_FLAG, * FROM ANACREDIT.DBO.CRD WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-03-31'
SELECT QUALIFICATION_FLAG, * FROM ANACREDIT.DBO.CRD_SUB WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-03-31'
SELECT QUALIFICATION_FLAG, * FROM ANACREDIT.DBO.CRD WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-02-29'
SELECT QUALIFICATION_FLAG, * FROM ANACREDIT.DBO.CRD_SUB WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-02-29'


select top 100
       REF_DT, QUALIFICATION_FLAG, SOURCE_SYSTEM_ID, CID, CNID, INSID, *
from anacredit.dbo.CID_SUB
where SOURCE_SYSTEM_ID='ADPTV' AND REF_DT='2024-03-31'
ORDER BY CID_SUB.QUALIFICATION_FLAG



SELECT QUALIFICATION_FLAG, * FROM ANACREDIT.DBO.IFD_SUB WHERE INSID='1250557ADPTV' AND REF_DT='2024-03-31'
SELECT QUALIFICATION_FLAG, * FROM ANACREDIT.DBO.CRD_SUB WHERE CID='ETHNCYNNXXX' AND REF_DT='2024-03-31'
SELECT * FROM [dbo].[ANACREDIT_IFD_DQ_ERR] WHERE INSID='1250557ADPTV' 
SELECT TOP 10 * FROM [dbo].[ANACREDIT_CID_DQ_ERR] WHERE  INSID='1250557ADPTV'--CID='ETHNCYNNXXX'


ADPTV          
            ETHNCYNNXXX
SET @CID = 'CITIGB2LXXX' ;		-- 4012117467	--έως 2019-01-31	
SET @CNID = '292403_292403';	-- HRSWP		--έως 2019-01-31
SET @OUTAM = ( select outam from ##temp_table_HSBC where CNID = @CNID ) ;


delete from CRD_SUB
where cid ='CITIUS33XXX' 
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[CrD_sub]
SELECT 
REF_DT, REP_A_ID, OBS_A_ID
,RECID
,CID
,NIDT, NID, AFM, IMO, GEMH, LEI, ESD, HOUID, IPUID, UPCID ,NAME, AStr, AC, ACTY, APC, ACTR, LF, ISctr, EA, SLP, DILP, ES ,DES, NE, BST, AT, AST, CR
,OLD, PR
,'1', '1', '1' -- HO , PAR, UP
,OCR, SRV
,CURRENT_TIMESTAMP INSERT_TIMESTAMP
,1 INSERT_ETL_RUN_ID
,SOURCE_SYSTEM_ID
,1 QUALIFICATION_FLAG
,@DATA_VERSION DATA_VERSION
,DEL_APPV_DIV_ID, DEPT_APPV_DIV_ID
,EM,PH
FROM CrD
WHERE cid ='CITIUS33XXX' and REF_DT = @ReportingDate
;


delete from CRD_SUB
where cid = @CID
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[CrD_sub]
SELECT 
@ReportingDate REF_DT, 'GR011' REP_A_ID, 'GR011' OBS_A_ID
,RECID
--,(select max(cast(recid as int))+1 from CRD where REF_DT = @ReportingDate) recid
,@cid CID
,NIDT, NID, AFM, IMO, GEMH, LEI, ESD, HOUID, IPUID, UPCID ,NAME, AStr, AC, ACTY, APC, ACTR, LF, ISctr, EA, SLP, DILP, ES ,DES, NE, BST, AT, AST, CR
,1 OLD
, PR, HO, PAR, UP, OCR, SRV
,CURRENT_TIMESTAMP INSERT_TIMESTAMP
,1 INSERT_ETL_RUN_ID
,SOURCE_SYSTEM_ID
,1 QUALIFICATION_FLAG
,@DATA_VERSION DATA_VERSION
,DEL_APPV_DIV_ID, DEPT_APPV_DIV_ID
,EM,PH
FROM CrD
WHERE CID = @CID and REF_DT = @ReportingDate --and QUALIFICATION_FLAG = 0
;

delete from CID_SUB
where CNID = @CNID
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[CID_sub]
SELECT @ReportingDate REF_DT
           ,'GR011'  REP_A_ID
           ,'GR011' OBS_A_ID
           ,case when crl =1 then (select max(cast(recid as int))+1 from CID_sub where REF_DT = @ReportingDate) 
				 when crl =2 then (select max(cast(recid as int))+2 from CID_sub where REF_DT = @ReportingDate) 
				 when crl =7 then (select max(cast(recid as int))+3 from CID_SUB where REF_DT = @ReportingDate) 
				end as recid
           ,cid 
           ,CNID 
           ,INSID
           ,CRL 
           ,CURRENT_TIMESTAMP INSERT_TIMESTAMP
           ,1 INSERT_ETL_RUN_ID
           ,SOURCE_SYSTEM_ID
           ,1 QUALIFICATION_FLAG
           ,@DATA_VERSION  DATA_VERSION
FROM CID_ADD 
WHERE CNID = @CNID
;

delete from CRID_SUB
where CID = @CID
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[CRID_sub]
SELECT @ReportingDate REF_DT
       ,'GR011'  REP_A_ID
       ,'GR011' OBS_A_ID
       ,(select max(cast(recid as int))+1 from CRID_SUB where REF_DT = @ReportingDate) recid
       ,cid 
       ,PD
       ,DS
       ,DSD 
       ,CURRENT_TIMESTAMP INSERT_TIMESTAMP
       ,1 INSERT_ETL_RUN_ID
       ,SOURCE_SYSTEM_ID
       ,1 QUALIFICATION_FLAG
       ,@DATA_VERSION  DATA_VERSION
FROM CRID_ADD 
WHERE CID = @CID
;

delete from AD_SUB
where CNID = @CNID
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[AD_sub]
SELECT @ReportingDate REF_DT
	,REP_A_ID, OBS_A_ID
	,(select max(cast(recid as int))+1 from AD_SUB where REF_DT = @ReportingDate) recid
	,ACC_ID, CNID, INSID
	,ACCNTC, BSR, ACCMRO, ACCMIMP, IMPS, IMPASSM, SRCENC, ACCMFVC
	,PERS, PRESD, PRVOB, FRBS, FRBSD, RECSD, PP
	,@OUTAM CAMM
	,CURRENT_TIMESTAMP INSERT_TIMESTAMP
	,1 INSERT_ETL_RUN_ID
	,SOURCE_SYSTEM_ID
	,1 QUALIFICATION_FLAG
	,@DATA_VERSION DATA_VERSION
FROM AD_ADD 
WHERE CNID = @CNID
;

delete from IFD_SUB
where CNID = @CNID
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[IFD_sub]
SELECT @ReportingDate REF_DT
,REP_A_ID, OBS_A_ID
,(select max(cast(recid as int))+1 from IFD_SUB where REF_DT = @ReportingDate) recid
, ACC_ID, CNID, INSID
,INST, AMRT, CUR, FDRCY, INCD, INSEOD, INTRC, INTRF
,INTRRF, INTRSM, INTRT, LFMD, TAM, PF
,PFL, PRPS, RCRS, REFD, STLD, SUBD
,SCID, RPR, FVCCR, INTRD, INTRRD
,INSTDS, INSTDSD, TRAM, ARRRS
,PDD, SECT
,@OUTAM OUTAM
,INTRACC, OBSAM
,CURRENT_TIMESTAMP INSERT_TIMESTAMP
,1 INSERT_ETL_RUN_ID
,SOURCE_SYSTEM_ID
,1 QUALIFICATION_FLAG
,@DATA_VERSION DATA_VERSION
,OPB, OOB, AMP, INSTST
FROM IFD_ADD 
WHERE CNID = @CNID
;

delete from JLD_SUB
where CNID = @CNID
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[JLD_sub]
SELECT @ReportingDate REF_DT
,REP_A_ID, OBS_A_ID
,(select max(cast(recid as int))+1 from JLD_SUB where REF_DT = @ReportingDate) recid
,CID, CNID, INSID, JLBAM
,CURRENT_TIMESTAMP INSERT_TIMESTAMP
,1 INSERT_ETL_RUN_ID
,SOURCE_SYSTEM_ID
,1 QUALIFICATION_FLAG
,@DATA_VERSION DATA_VERSION

FROM JLD_ADD 
WHERE CNID = @CNID
;


delete from IPRD_SUB
where CNID = @CNID
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[IPRD_sub]
SELECT @ReportingDate REF_DT
,REP_A_ID, OBS_A_ID
,(select max(cast(recid as int))+1 from IPRD_SUB where REF_DT = @ReportingDate) recid
, CNID, INSID, PRID, PRAV, PR3PPRI
,CURRENT_TIMESTAMP INSERT_TIMESTAMP
,1 INSERT_ETL_RUN_ID
,SOURCE_SYSTEM_ID
,1 QUALIFICATION_FLAG
,@DATA_VERSION DATA_VERSION

FROM IPRD_ADD 
WHERE CNID = @CNID
;

delete from PRD_SUB
where PRID IN ( SELECT PRID FROM IPRD_ADD WHERE CNID = @CNID)
and REF_DT = @ReportingDate
;
INSERT INTO [dbo].[PRD_sub]
SELECT @ReportingDate REF_DT
,REP_A_ID, OBS_A_ID
,(select max(cast(recid as int))+1 from PRD_SUB where REF_DT = @ReportingDate) recid
,PRID, PRCID, PRT, PRV, PRVT, PRVA, RECL, PRVD, PRMD, PROV, PROVD
,CURRENT_TIMESTAMP INSERT_TIMESTAMP
,1 INSERT_ETL_RUN_ID
,SOURCE_SYSTEM_ID
,1 QUALIFICATION_FLAG
,@DATA_VERSION DATA_VERSION
FROM PRD_ADD 
WHERE PRID IN ( SELECT PRID FROM IPRD_ADD WHERE CNID = @CNID)
;
"