USE Anacredit
SELECT * FROM [src].[FILE_TREASURY_PRTF] 
WHERE CounterParty='ETHNCYNNXXX'
SELECT QUALIFICATION_FLAG, * from anacredit.dbo.CID WHERE INSID='1224596ADPTV' AND REF_DT='2023-12-31'
SELECT QUALIFICATION_FLAG, * from anacredit.dbo.CID_SUB WHERE INSID='1224596ADPTV' AND REF_DT='2023-12-31'


DECLARE @ReportingDate datetime
;
SET @ReportingDate = ?

DECLARE @RunID int;
SET @RunID = ?


DECLARE @REP_A_ID nvarchar(30);
SET @REP_A_ID= 'GR011';

DECLARE @OBS_A_ID nvarchar(30);
SET @OBS_A_ID= 'GR011';


    select DISTINCT
        @ReportingDate As REF_DT 
, @REP_A_ID AS REP_A_ID
, @OBS_A_ID AS OBS_A_ID
, NULL AS RECID
, 'N/A' AS ACC_ID
, CAST( rtrim(ltrim(FILE_TREASURY_PRTF.CounterParty_Instrument)) AS nvarchar(30) ) AS CNID
, CAST( rtrim(ltrim(FILE_TREASURY_PRTF.InstrumentID)) + 'ADPTV' AS nvarchar(30) ) AS INSID
, REF_INST_TYPE.INST AS INST
, CASE
WHEN REF_INST_TYPE.INST ='1000' THEN '4' 
ELSE '5' 
END AS AMRT
, CAST(FILE_TREASURY_PRTF.CCY AS CHAR(3)) AS CUR
, CAST('2' AS CHAR(1)) AS FDRCY
, CAST(FILE_TREASURY_PRTF.DealDate AS datetime) AS INCD
, CAST('1900-01-01' AS datetime) AS INSEOD
, NULL AS INTRC
, NULL AS INTRF
, CASE 
WHEN LegType = 'FIXED' THEN ''
WHEN GL_Product = 'Segmented Loans' THEN '1'
ELSE '12'
END AS INTRRF
, CASE
WHEN FILE_TREASURY_PRTF.LegType = 'FLOAT' THEN CAST(FILE_TREASURY_PRTF.IntRate_Spread AS NUMERIC(10,5))
END AS INTRSM
, CASE 
WHEN FILE_TREASURY_PRTF.LegType ='FLOAT' THEN '2' 
ELSE '1'
END  AS INTRT
, FILE_TREASURY_PRTF.EndDate AS LFMD
--,CAST(ISNULL(IFD.TAM, abs(FILE_TREASURY_PRTF.OSPrincipal) ) AS NUMERIC(18,2)) AS TAM --md20191209
, ROUND(CAST(ISNULL(IFD.TAM, abs(FILE_TREASURY_PRTF.OSPrincipal) )  AS NUMERIC(18,2))/ case when (FILE_TREASURY_PRTF.ccy='EUR' or EDW_com_FX_RATES.FX_ECBREF_PCT = 0) THEN 1 else EDW_com_FX_RATES.FX_ECBREF_PCT end,2) AS TAM --md20191209
, ISNULL(REF_PF_TYPE.PF,'15') AS PF
, CAST('2' AS CHAR(1)) AS PFL 
, CAST('11' AS CHAR(2)) AS PRPS 
, CAST('1' AS CHAR(1)) AS RCRS 
, ISNULL(REF_REFD_TYPE.REFD,'') AS REFD
, CAST(FILE_TREASURY_PRTF.StartDate AS datetime) AS STLD
, CAST('2' AS CHAR(1)) AS SUBD
, CAST('' AS NVARCHAR(100)) AS SCID
, CASE 
WHEN DATEDIFF(Day,FILE_TREASURY_PRTF.StartDate,FILE_TREASURY_PRTF.EndDate) =1 THEN '1' 
ELSE '2' 
END AS RPR
, CAST(0 AS numeric(18,2)) as FVCCR
, CASE 
WHEN ISNULL(FILE_TREASURY_PRTF.Contract_Rate,0)=0 THEN CAST(FILE_TREASURY_PRTF.RepoRate / 100.0 AS NUMERIC(10,5)) 
ELSE CAST(FILE_TREASURY_PRTF.Contract_Rate AS NUMERIC(10,5))
END AS INTRD
, CASE 
WHEN  FILE_TREASURY_PRTF.LegType = 'FIXED'
            OR FILE_TREASURY_PRTF.PayDateRec < @ReportingDate
            OR DATEDIFF(Day, FILE_TREASURY_PRTF.StartDate,FILE_TREASURY_PRTF.EndDate) =1 THEN '1900-01-01'
ELSE FILE_TREASURY_PRTF.PayDateRec
END AS INTRRD
, CAST('' AS CHAR(2)) AS INSTDS
, CAST('1900-01-01'AS datetime)INSTDSD
, CAST(0 AS numeric(18,2)) AS TRAM 
, CAST(0 AS numeric(18,2)) AS ARRRS 
, CAST('1900-01-01' AS datetime) AS PDD 
, CAST('7' AS CHAR(1)) AS SECT 
, ROUND(CAST( abs(FILE_TREASURY_PRTF.OSPrincipal) AS numeric(18,2))/ case when (FILE_TREASURY_PRTF.ccy='EUR' or EDW_com_FX_RATES.FX_ECBREF_PCT = 0) THEN 1 else EDW_com_FX_RATES.FX_ECBREF_PCT end,2) AS OUTAM  --md20190402
, ROUND(CAST(FILE_TREASURY_PRTF.AccrualBal AS NUMERIC(18,2)) / case when (FILE_TREASURY_PRTF.ccy='EUR' or EDW_com_FX_RATES.FX_ECBREF_PCT = 0) THEN 1 else EDW_com_FX_RATES.FX_ECBREF_PCT end,2) AS INTRACC
, CASE WHEN REF_INST_TYPE.INST NOT IN (1001, 51, 1002) THEN NULL ELSE CAST(0 AS numeric(18,2)) END [OBSAM]
, CURRENT_TIMESTAMP AS INSERT_TIMESTAMP
, @RunID as INSERT_ETL_RUN_ID
, 'ADPTV'  AS [SOURCE_SYSTEM_ID]
, 0 as QUALIFICATION_FLAG
, cast((CONVERT(NVARCHAR(8),@ReportingDate ,112) + '0' + cast(@RunID as nvarchar(1)))as nvarchar(20)) [DATA_VERSION]
    FROM [src].[FILE_TREASURY_PRTF] FILE_TREASURY_PRTF

        INNER JOIN [src].[EDW_cst_CST_ORG] org /*nomika proswpa*/
        ON CAST(org.CST_ID AS NVARCHAR(258)) = CAST(FILE_TREASURY_PRTF.[SyDiPel] AS NVARCHAR(255))

        --dbo.REF_INST_TYPE as REF_INST_TYPE
        LEFT JOIN dbo.REF_INST_TYPE REF_INST_TYPE
        ON FILE_TREASURY_PRTF.GL_Product =REF_INST_TYPE.ACC_SUB_CTG_ID

        --dbo.IFD as IFD
        LEFT JOIN dbo.IFD IFD
        ON InstrumentID+'ADPTV' = IFD.INSID
            AND IFD.REF_DT = DATEADD(MONTH,-1,@ReportingDate)

        ---dbo.REF_PF_TYPE AS REF_PF_TYPE
        LEFT JOIN dbo.REF_PF_TYPE REF_PF_TYPE
        ON FILE_TREASURY_PRTF.PayFreqRec = REF_PF_TYPE.DMND_FREQ

        --dbo.REF_REFD_TYPE as REF_REFD_TYPE
        LEFT JOIN dbo.REF_REFD_TYPE REF_REFD_TYPE
        ON REF_REFD_TYPE.RATE_CTG_ID = FILE_TREASURY_PRTF.IndexRec

        --[src].[EDW_com_FX_RATES] as EDW_com_FX_RATES
        LEFT JOIN [src].[EDW_com_FX_RATES] (NOLOCK)  EDW_com_FX_RATES
        ON FILE_TREASURY_PRTF.CCY = EDW_com_FX_RATES.FX_CCY_DESCR and EDW_com_FX_RATES.FX_DATE > @ReportingDate
            AND EDW_com_FX_RATES.DT_REC <= @ReportingDate
    WHERE FILE_TREASURY_PRTF.GL_Product <> 'Subord Loans'
        and FILE_TREASURY_PRTF.StartDate <= @ReportingDate

    --------------------------------------------------------------------------------
    --md20230119 for swiftcodes without SYDIPEL
union all
    select DISTINCT
        @ReportingDate As REF_DT 
, @REP_A_ID AS REP_A_ID
, @OBS_A_ID AS OBS_A_ID
, NULL AS RECID
, 'N/A' AS ACC_ID
, CAST( rtrim(ltrim(FILE_TREASURY_PRTF.CounterParty_Instrument)) AS nvarchar(30) ) AS CNID
, CAST( rtrim(ltrim(FILE_TREASURY_PRTF.InstrumentID)) + 'ADPTV' AS nvarchar(30) ) AS INSID
, REF_INST_TYPE.INST AS INST
, CASE
WHEN REF_INST_TYPE.INST ='1000' THEN '4' 
ELSE '5' 
END AS AMRT
, CAST(FILE_TREASURY_PRTF.CCY AS CHAR(3)) AS CUR
, CAST('2' AS CHAR(1)) AS FDRCY
, CAST(FILE_TREASURY_PRTF.DealDate AS datetime) AS INCD
, CAST('1900-01-01' AS datetime) AS INSEOD
, NULL AS INTRC
, NULL AS INTRF
, CASE 
WHEN LegType = 'FIXED' THEN ''
WHEN GL_Product = 'Segmented Loans' THEN '1'
ELSE '12'
END AS INTRRF
, CASE
WHEN FILE_TREASURY_PRTF.LegType = 'FLOAT' THEN CAST(FILE_TREASURY_PRTF.IntRate_Spread AS NUMERIC(10,5))
END AS INTRSM
, CASE 
WHEN FILE_TREASURY_PRTF.LegType ='FLOAT' THEN '2' 
ELSE '1'
END  AS INTRT
, FILE_TREASURY_PRTF.EndDate AS LFMD
, ROUND(CAST(ISNULL(IFD.TAM, abs(FILE_TREASURY_PRTF.OSPrincipal) )  AS NUMERIC(18,2))/ case when (FILE_TREASURY_PRTF.ccy='EUR' or EDW_com_FX_RATES.FX_ECBREF_PCT = 0) THEN 1 else EDW_com_FX_RATES.FX_ECBREF_PCT end,2) AS TAM --md20191209
, ISNULL(REF_PF_TYPE.PF,'15') AS PF
, CAST('2' AS CHAR(1)) AS PFL 
, CAST('11' AS CHAR(2)) AS PRPS 
, CAST('1' AS CHAR(1)) AS RCRS 
, ISNULL(REF_REFD_TYPE.REFD,'') AS REFD
, CAST(FILE_TREASURY_PRTF.StartDate AS datetime) AS STLD
, CAST('2' AS CHAR(1)) AS SUBD
, CAST('' AS NVARCHAR(100)) AS SCID
, CASE 
WHEN DATEDIFF(Day,FILE_TREASURY_PRTF.StartDate,FILE_TREASURY_PRTF.EndDate) =1 THEN '1' 
ELSE '2' 
END AS RPR
, CAST(0 AS numeric(18,2)) as FVCCR
, CASE 
WHEN ISNULL(FILE_TREASURY_PRTF.Contract_Rate,0)=0 THEN CAST(FILE_TREASURY_PRTF.RepoRate / 100.0 AS NUMERIC(10,5)) 
ELSE CAST(FILE_TREASURY_PRTF.Contract_Rate AS NUMERIC(10,5))
END AS INTRD
, CASE 
WHEN  FILE_TREASURY_PRTF.LegType = 'FIXED'
            OR FILE_TREASURY_PRTF.PayDateRec < @ReportingDate
            OR DATEDIFF(Day, FILE_TREASURY_PRTF.StartDate,FILE_TREASURY_PRTF.EndDate) =1 THEN '1900-01-01'
ELSE FILE_TREASURY_PRTF.PayDateRec
END AS INTRRD
, CAST('' AS CHAR(2)) AS INSTDS
, CAST('1900-01-01'AS datetime)INSTDSD
, CAST(0 AS numeric(18,2)) AS TRAM 
, CAST(0 AS numeric(18,2)) AS ARRRS 
, CAST('1900-01-01' AS datetime) AS PDD 
, CAST('7' AS CHAR(1)) AS SECT 
, ROUND(CAST( abs(FILE_TREASURY_PRTF.OSPrincipal) AS numeric(18,2))/ case when (FILE_TREASURY_PRTF.ccy='EUR' or EDW_com_FX_RATES.FX_ECBREF_PCT = 0) THEN 1 else EDW_com_FX_RATES.FX_ECBREF_PCT end,2) AS OUTAM  --md20190402
, ROUND(CAST(FILE_TREASURY_PRTF.AccrualBal AS NUMERIC(18,2)) / case when (FILE_TREASURY_PRTF.ccy='EUR' or EDW_com_FX_RATES.FX_ECBREF_PCT = 0) THEN 1 else EDW_com_FX_RATES.FX_ECBREF_PCT end,2) AS INTRACC
, CASE WHEN REF_INST_TYPE.INST NOT IN (1001, 51, 1002) THEN NULL ELSE CAST(0 AS numeric(18,2)) END [OBSAM]
, CURRENT_TIMESTAMP AS INSERT_TIMESTAMP
, @RunID as INSERT_ETL_RUN_ID
, 'ADPTV'  AS [SOURCE_SYSTEM_ID]
, 0 as QUALIFICATION_FLAG
, cast((CONVERT(NVARCHAR(8),@ReportingDate ,112) + '0' + cast(@RunID as nvarchar(1)))as nvarchar(20)) [DATA_VERSION]
    FROM [src].[FILE_TREASURY_PRTF] FILE_TREASURY_PRTF

        left JOIN [src].[EDW_cst_CST_ORG] org /*nomika proswpa*/
        ON CAST(org.CST_ID AS NVARCHAR(258)) = CAST(FILE_TREASURY_PRTF.[SyDiPel] AS NVARCHAR(255))

        --dbo.REF_INST_TYPE as REF_INST_TYPE
        LEFT JOIN dbo.REF_INST_TYPE REF_INST_TYPE
        ON FILE_TREASURY_PRTF.GL_Product =REF_INST_TYPE.ACC_SUB_CTG_ID

        --dbo.IFD as IFD
        LEFT JOIN dbo.IFD IFD
        ON InstrumentID+'ADPTV' = IFD.INSID
            AND IFD.REF_DT = DATEADD(MONTH,-1,@ReportingDate)

        ---dbo.REF_PF_TYPE AS REF_PF_TYPE
        LEFT JOIN dbo.REF_PF_TYPE REF_PF_TYPE
        ON FILE_TREASURY_PRTF.PayFreqRec = REF_PF_TYPE.DMND_FREQ

        --dbo.REF_REFD_TYPE as REF_REFD_TYPE
        LEFT JOIN dbo.REF_REFD_TYPE REF_REFD_TYPE
        ON REF_REFD_TYPE.RATE_CTG_ID = FILE_TREASURY_PRTF.IndexRec

        --[src].[EDW_com_FX_RATES] as EDW_com_FX_RATES
        LEFT JOIN [src].[EDW_com_FX_RATES] (NOLOCK)  EDW_com_FX_RATES
        ON FILE_TREASURY_PRTF.CCY = EDW_com_FX_RATES.FX_CCY_DESCR and EDW_com_FX_RATES.FX_DATE > @ReportingDate
            AND EDW_com_FX_RATES.DT_REC <= @ReportingDate

    WHERE FILE_TREASURY_PRTF.GL_Product <> 'Subord Loans'
        and FILE_TREASURY_PRTF.StartDate <= @ReportingDate
        and CAST(FILE_TREASURY_PRTF.SyDiPel AS NVARCHAR(30)) = CAST(FILE_TREASURY_PRTF.SwiftBICCode AS NVARCHAR(30))
        and org.CST_ID is null
;